package com.example.data

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.io.Serializable

@Entity(tableName = "projects")
data class Project(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val clientName: String,
    val clientPhone: String,
    val clientEmail: String,
    val clientAddress: String,
    val typeOfWork: String,
    val width: Double,
    val height: Double,
    val depth: Double,
    val color: String,
    val glassType: String,
    val glassThickness: String,
    val notes: String,
    val imagePaths: String = "", // Comma-separated list of image URIs/paths
    val calculatedBudget: Double = 0.0,
    val aiQuoteBreakdown: String = "", // Detailed professional text generated by AI
    val timestamp: Long = System.currentTimeMillis()
) : Serializable
